version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - asyncpg
  - auditconfig
  - dedup
  - Dedup
  - fastapi
  - govulncheck
  - Hono
  - mypy
  - Nuxt
  - Pydantic
  - pyproject
  - pytest
  - tbls
  - uvx
  - venv
  - whatifwedigdeeper
ignoreWords: []
import: []
