source "https://rubygems.org"

ruby ">= 3.3.0"

gem "bootsnap", "1.19.0", require: false
gem "pg", "1.6.2"
gem "puma", "7.2.1"
gem "rack-cors", "3.0.0"
gem "rails", "8.0.4.1"

group :development, :test do
  gem "bundler-audit", "0.9.2", require: false
  gem "debug", "1.11.0", require: false
  gem "rspec-rails", "8.0.2"
  gem "rubocop", "1.82.0", require: false
  gem "rubocop-rails", "2.34.1", require: false
end
