name: Verify PR

on:
  pull_request:
    branches: [main]


jobs:
  build:
    name: verify-pr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js from .node-version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Run Security Audit
        run: npm run audit:ci

      - name: Install npm packages
        run: npm run ci:all

      - name: Lint
        run: npm run lint:all

      - name: Build
        run: npm run build:all

      - name: Test
        run: npm run test:all
